[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Sam Radhakrishnan <sk09idm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num-bigint = "0.3.1"
num-traits = "0.2"
